### ISSUE TITLE
Missing point_plot model annotation if X variable has more than 3 categories

### ISSUE THREAD

**Issue by noew** [dtkaplan/math300#6]
The model annotation is not displayed for some values if the X variable has more than 3 categories. For example, 
`LSTbook::MPG |> point_plot(mpg_comb ~ drive, annot = "model", point_ink = 0.1)`
![image](https://github.com/user-attachments/assets/2ba17aa3-d4df-4427-882a-e4a2f688088e)

**Comment by dtkaplan** [comment]
Thanks for pointing this out.  I'll be able to fix it, but since I just pushed a new version of the package to CRAN this morning, it may not appear on CRAN for some weeks.

**Comment by noew** [comment]
Thanks for your work on this package, and the textbook. I've been using it with my students this semester with good success.

**Comment by dtkaplan** [comment]
Glad to hear that the textbook has been working out well. 

I've pushed a fix for this issue to github, adding a description in the NEWS file for the package.
